#!/bin/bash

#checkout the vim plugins and copy the .vimrc
function update_plugins
{
	if [ ! -d $1 ]; then
		echo "$1 does not exist, please check!"
		exit	
	fi
	cd $1
	for file in `ls`; do
		if [ -d $file -a -d $file/.git ]; then
			echo $file
			cd $file && git pull && cd ..
		fi
	done
	cd ..
}
cp -rf vimrc ~/.vimrc
if [ ! -d ~/.vim/bundle/vundle ]; then 
	git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

vim +BundleInstall +qall

#update_plugins "$HOME/.vim/bundle"
