#!/bin/bash

#checkout the vim plugins and copy the .vimrc

VIMRC_BAK="vimrc_old"

function update_plugins
{
	vim +BundleInstall! +qall
}

function install_plugins
{
	echo "********** Installing vim plugins **********"

	if [ -f $HOME/.vimrc ]; then
		echo "********** Backup the exist .vimrc to $VIMRC_BAK  **********"		
		mv $HOME/.vimrc $HOME/$VIMRC_BAK
	fi

	cp -rf vimrc_install $HOME/.vimrc

	if [ ! -d $HOME/.vim/bundle/vundle ]; then 
		git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
	fi

	vim +BundleInstall +qall

	cp -rf bundle $HOME/.vim/

	cat vimrc >> $HOME/.vimrc

	echo "********** Installation Done! **********"
	echo "* Notes: ack.vim required \"ack\" in your system, please read the documentations in http://betterthangrep.com/"
 
}

function Usage
{
	echo "Usage: $0"
	echo "$0 update"
}
if [ $# -eq 0 ]; then 
	install_plugins
	exit
fi

if [ $# -gt 1 ]; then
	Usage
	exit 
fi

if [ $1 = "update" ]; then
	update_plugins "$HOME/.vim/bundle"
else
	Usage
fi

